### ISSUE TITLE
Issues with balena etcher

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [Lassulus/nix-autobahn#11]
Maybe this is a issue with the way balena etcher calls upon their dependencies but I figured i would post this here in case this is a issue with the project, I love this project by the way!

```
[spiderunderurbed@daspidercave:~/Desktop]$ ../nix-autobahn/nix-autobahn BalenaEtcher.AppImage
        not a dynamic executable
warning: unknown setting 'access-token'
/home/spiderunderurbed/Desktop/BalenaEtcher.AppImage: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory

[spiderunderurbed@daspidercave:~/Desktop]$ 
```

**Comment by Lassulus** [comment]
this seems to be an app-image and not a dynamically linked executable. you just need appimage-run to run it: https://wiki.nixos.org/wiki/Appimage
