### ISSUE TITLE
I essentially rewrote nix-autobahn in Rust

### ISSUE THREAD

**Issue by wucke13** [Lassulus/nix-autobahn#7]
Do you have any interest in merging that? You can checkout my code here https://github.com/wucke13/nix-autobahn/tree/rust. See this video for the UI:

![nix-autobahn-riir](https://user-images.githubusercontent.com/20400405/71426739-aacdcb00-26ae-11ea-8cb0-f4bd6264c6ca.gif)

Currently the whole code is a single src file, imperatively written. One could think of using a more object oriented approach, of course. Binary links statically (though `nix-locate` has to be in the `$PATH`).

**Comment by wucke13** [comment]
@Lassulus ping

**Comment by Lassulus** [comment]
ah whupps, I'm so lazy
sadly I'm not very proficient in rust, I would suggest you make a new project or a fork an maintain a rust version of it since you would be a better maintainer than me ;D

**Comment by wucke13** [comment]
Remember, many programming languages claim laziness as a feature!
Are you ok with the Rust project keeping the nix-autobahn name? I like it a lot :laughing:, and I don't want to inflate the open source project namespace any further

**Comment by Lassulus** [comment]
sure, take the name :D nix-autobahn was basically a 1-day rewrite of some other implementation in perl if I remeber correctly
